// Front/Front-React/src/components/palestrantes/PalestrantesPage.tsx
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import {
  AlertMotion,
  EmptyState,
  ListStagger,
  ListStaggerItem,
  PageEnter,
  SkeletonShimmer,
} from "@/shared/motion";
import { ConfirmDialog } from "@/shared/ConfirmDialog";
import { LoadingSpinner } from "@/components/LoadingSpinner";
import { useDebouncedValue } from "@/hooks/useDebouncedValue";
import type { Palestrante } from "@/models";
import { PAGE_SIZES, type PageSize } from "@/models/pagination";
import { canWrite, isAuthenticated } from "@/services/authToken";
import { palestranteService } from "@/services/palestranteService";
import { isRemoteImageUrl } from "@/utils/imageUrl";

const inputClass =
  "w-full rounded-[length:var(--radius-control)] border border-line bg-panel px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/20";
const btnPrimary =
  "inline-flex items-center justify-center rounded-[length:var(--radius-control)] bg-accent px-4 py-2 text-sm font-medium text-white transition-transform hover:bg-accent-dark active:scale-[0.98] disabled:cursor-not-allowed disabled:opacity-60";
const btnOutline =
  "inline-flex items-center justify-center rounded-[length:var(--radius-control)] border border-line bg-panel px-4 py-2 text-sm font-medium text-ink transition-colors hover:bg-surface";
const btnSmAccent =
  "inline-flex items-center justify-center rounded-[length:var(--radius-control)] border border-accent/30 bg-panel px-2 py-1 text-xs font-medium text-accent-dark hover:bg-accent-soft";
const btnSmDanger =
  "inline-flex items-center justify-center rounded-[length:var(--radius-control)] border border-danger-border bg-panel px-2 py-1 text-xs font-medium text-danger hover:bg-danger-soft";

export function PalestrantesPage() {
  const loggedIn = isAuthenticated();
  const writeAllowed = canWrite();
  const [palestrantes, setPalestrantes] = useState<Palestrante[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [qInput, setQInput] = useState("");
  const [qFilter, setQFilter] = useState("");
  const debouncedQ = useDebouncedValue(qInput, 350);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState<PageSize>(10);
  const [totalPages, setTotalPages] = useState(0);
  const [reloadToken, setReloadToken] = useState(0);
  const [pendingDelete, setPendingDelete] = useState<{
    id: number;
    nome: string;
  } | null>(null);

  useEffect(() => {
    // Only commit when debounce has caught up to the live input (avoids
    // overwriting immediate submit/clear with a stale pending term).
    if (debouncedQ !== qInput) return;
    const next = debouncedQ.trim();
    if (next === qFilter) return;
    setPage(1);
    setQFilter(next);
  }, [debouncedQ, qInput, qFilter]);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    void palestranteService
      .getAll({
        page,
        pageSize,
        q: qFilter.trim() || undefined,
      })
      .then((data) => {
        if (cancelled) return;
        setPalestrantes(data?.items ?? []);
        setTotalPages(data?.totalPages ?? 0);
        if (data?.page != null && data.page !== page) setPage(data.page);
      })
      .catch(() => {
        if (!cancelled) setError("Não foi possível carregar palestrantes.");
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [page, pageSize, qFilter, reloadToken]);

  async function confirmDelete() {
    if (!pendingDelete) return;
    const { id } = pendingDelete;
    setPendingDelete(null);
    setSuccess(null);
    try {
      await palestranteService.delete(id);
      setSuccess("Palestrante excluído com sucesso.");
      setPage(1);
      setReloadToken((t) => t + 1);
    } catch {
      alert("Erro ao deletar palestrante.");
    }
  }

  function onFilter() {
    setPage(1);
    setQFilter(qInput.trim());
  }

  const alertDangerClass =
    "rounded-[length:var(--radius-control)] border border-danger-border bg-danger-soft px-4 py-3 text-sm text-danger";
  const alertSuccessClass =
    "rounded-[length:var(--radius-control)] border border-line bg-surface px-4 py-3 text-sm text-accent-dark";

  return (
    <PageEnter>
      <div className="flex min-w-0 flex-col gap-6">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Palestrantes</h1>
          <p className="mt-1 text-sm text-muted">
            Lista, busca e gerenciamento básico.
          </p>
        </div>
        {writeAllowed ? (
          <Link to="/palestrantes/new" className={`${btnPrimary} motion-press`}>
            Novo palestrante
          </Link>
        ) : loggedIn ? null : (
          <Link to="/login" className={`${btnPrimary} motion-press`}>
            Entrar para criar
          </Link>
        )}
      </div>

      {loggedIn && !writeAllowed && (
        <p className="rounded-[length:var(--radius-control)] border border-line bg-surface px-4 py-3 text-sm text-muted">
          Acesso somente leitura. É necessária a role User para cadastrar ou
          editar palestrantes.
        </p>
      )}

      <AlertMotion show={!!success} className={alertSuccessClass}>
        {success}
      </AlertMotion>

      <form
        className="flex flex-wrap items-end gap-3 rounded-[length:var(--radius-control)] border border-line bg-panel p-4"
        onSubmit={(e) => {
          e.preventDefault();
          onFilter();
        }}
      >
        <label className="flex w-full min-w-0 flex-1 flex-col gap-2 text-sm">
          <span className="font-medium text-ink">Buscar</span>
          <input
            className={inputClass}
            value={qInput}
            onChange={(e) => setQInput(e.target.value)}
            placeholder="Digite para buscar"
          />
        </label>
        <button type="submit" className={`${btnPrimary} motion-press`}>
          Buscar
        </button>
        <button
          type="button"
          className={btnOutline}
          onClick={() => {
            setQInput("");
            setPage(1);
            setQFilter("");
          }}
        >
          Limpar
        </button>
      </form>

      <LoadingSpinner loading={loading} variant="page" />
      <AlertMotion show={!!error} className={alertDangerClass}>
        {error}
      </AlertMotion>

      {!error && (
        <>
          {loading ? (
            <div className="overflow-x-auto rounded-[length:var(--radius-control)] border border-line bg-panel">
              <SkeletonShimmer rows={5} className="p-4" />
            </div>
          ) : (
            <>
              {palestrantes.length > 0 && (
                <div className="overflow-x-auto rounded-[length:var(--radius-control)] border border-line bg-panel">
                  <table className="w-full min-w-[560px] text-sm">
                    <thead>
                      <tr className="border-b border-line bg-surface text-left text-muted">
                        <th className="px-4 py-3 font-medium">Imagem</th>
                        <th className="px-4 py-3 font-medium">Nome</th>
                        <th className="px-4 py-3 font-medium">E-mail</th>
                        <th className="px-4 py-3 font-medium">Telefone</th>
                        <th className="px-4 py-3 font-medium">Ações</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-line">
                      <ListStagger>
                        {palestrantes.map((palestrante, index) => (
                          <ListStaggerItem
                            key={palestrante.id}
                            index={index}
                            className="contents"
                          >
                            <tr className="hover:bg-surface">
                              <td className="px-4 py-3">
                                {isRemoteImageUrl(palestrante.imagemURL) ? (
                                  <img
                                    src={palestrante.imagemURL}
                                    alt=""
                                    className="h-10 w-10 rounded object-cover"
                                    onError={(event) => {
                                      event.currentTarget.style.display = "none";
                                    }}
                                  />
                                ) : (
                                  <span className="text-muted">—</span>
                                )}
                              </td>
                              <td className="px-4 py-3 font-medium">
                                {writeAllowed ? (
                                  <Link
                                    to={`/palestrantes/${palestrante.id}`}
                                    className="font-medium text-accent-dark hover:underline"
                                  >
                                    {palestrante.nome}
                                  </Link>
                                ) : (
                                  palestrante.nome
                                )}
                              </td>
                              <td className="px-4 py-3">{palestrante.email}</td>
                              <td className="px-4 py-3">{palestrante.telefone}</td>
                              <td className="px-4 py-3">
                                {writeAllowed ? (
                                  <div className="flex flex-wrap gap-2">
                                    <Link
                                      to={`/palestrantes/${palestrante.id}`}
                                      className={btnSmAccent}
                                    >
                                      Editar
                                    </Link>
                                    <button
                                      type="button"
                                      className={btnSmDanger}
                                      onClick={() =>
                                        setPendingDelete({
                                          id: palestrante.id,
                                          nome: palestrante.nome,
                                        })
                                      }
                                    >
                                      Excluir
                                    </button>
                                  </div>
                                ) : loggedIn ? (
                                  <span className="text-muted">—</span>
                                ) : (
                                  <Link to="/login" className={btnSmAccent}>
                                    Entrar para editar
                                  </Link>
                                )}
                              </td>
                            </tr>
                          </ListStaggerItem>
                        ))}
                      </ListStagger>
                    </tbody>
                  </table>
                </div>
              )}

              <EmptyState
                show={palestrantes.length === 0}
                className="rounded-[length:var(--radius-control)] border border-line bg-panel px-4 py-8 text-center text-sm text-muted"
              >
                Nenhum palestrante encontrado.
              </EmptyState>

              {totalPages > 0 && (
            <div className="flex flex-wrap items-center justify-between gap-3">
              <label className="flex items-center gap-2 text-sm">
                <span className="font-medium text-muted">Itens por página</span>
                <select
                  className={inputClass}
                  value={pageSize}
                  onChange={(event) => {
                    setPageSize(Number(event.target.value) as PageSize);
                    setPage(1);
                  }}
                >
                  {PAGE_SIZES.map((size) => (
                    <option key={size} value={size}>
                      {size}
                    </option>
                  ))}
                </select>
              </label>
              <div className="flex flex-wrap items-center gap-3">
                <button
                  type="button"
                  className={btnOutline}
                  disabled={page <= 1}
                  onClick={() => setPage((current) => current - 1)}
                >
                  Anterior
                </button>
                <span className="text-sm text-muted">
                  Página {page} de {totalPages}
                </span>
                <button
                  type="button"
                  className={btnOutline}
                  disabled={page >= totalPages}
                  onClick={() => setPage((current) => current + 1)}
                >
                  Próxima
                </button>
              </div>
            </div>
              )}
            </>
          )}
        </>
      )}

      <ConfirmDialog
        open={pendingDelete !== null}
        title="Excluir palestrante"
        message={
          pendingDelete ? `Deseja deletar "${pendingDelete.nome}"?` : ""
        }
        confirmLabel="Excluir"
        onConfirm={() => void confirmDelete()}
        onCancel={() => setPendingDelete(null)}
      />
      </div>
    </PageEnter>
  );
}

// Front/Front-Vue/src/components/palestrantes/PalestrantesPage.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import { useRouter } from "vue-router";
import type { Palestrante } from "../../Models/Palestrante";
import { canWrite, isAuthenticated } from "../../services/authToken";
import palestranteService from "../../services/palestranteService";
import ConfirmDialog from "../../shared/ConfirmDialog.vue";
import LoadingSpinner from "../common/LoadingSpinner.vue";
import PageEnter from "../../shared/motion/PageEnter.vue";
import AlertMotion from "../../shared/motion/AlertMotion.vue";
import ListStagger from "../../shared/motion/ListStagger.vue";
import SkeletonShimmer from "../../shared/motion/SkeletonShimmer.vue";
import EmptyState from "../../shared/motion/EmptyState.vue";
import { debounce } from "../../utils/debounce";
import { isRemoteImageUrl } from "../../utils/imageUrl";
import { PAGE_SIZES, type PageSize } from "../../Models/pagination";

const SEARCH_DEBOUNCE_MS = 350;

const router = useRouter();
const items = ref<Palestrante[]>([]);
const loading = ref(false);
const error = ref<string | null>(null);
const success = ref<string | null>(null);
const pendingDelete = ref<Palestrante | null>(null);
const filterQ = ref("");
const page = ref(1);
const pageSize = ref<PageSize>(10);
const totalPages = ref(0);
const writeAllowed = computed(() => canWrite());
const isLoggedIn = computed(() => isAuthenticated());
let listRequestId = 0;

const paged = computed(() => ({
  items: items.value,
  page: page.value,
  pageSize: pageSize.value,
  totalPages: totalPages.value,
}));

const deleteMessage = computed(() =>
  pendingDelete.value
    ? `Deseja deletar "${pendingDelete.value.nome}"?`
    : "",
);

const debouncedSearch = debounce(() => {
  void load({ resetPage: true });
}, SEARCH_DEBOUNCE_MS);

watch(
  filterQ,
  () => {
    debouncedSearch();
  },
  { flush: "sync" },
);

async function load(opts?: { keepPage?: boolean; resetPage?: boolean }) {
  debouncedSearch.cancel();
  loading.value = true;
  error.value = null;
  if (opts?.resetPage || !opts?.keepPage) page.value = 1;
  const requestId = ++listRequestId;
  try {
    const { data } = await palestranteService.list({
      page: page.value,
      pageSize: pageSize.value,
      q: filterQ.value.trim() || undefined,
    });
    if (requestId !== listRequestId) return;
    items.value = data.items;
    page.value = data.page;
    totalPages.value = data.totalPages;
  } catch {
    if (requestId !== listRequestId) return;
    error.value = "Não foi possível carregar palestrantes.";
  } finally {
    if (requestId === listRequestId) loading.value = false;
  }
}

function goToPage(next: number) {
  page.value = next;
  void load({ keepPage: true });
}

function onPageSizeChange() {
  page.value = 1;
  void load({ keepPage: true });
}

function buscar() {
  debouncedSearch.cancel();
  void load({ resetPage: true });
}

function limparFiltro() {
  filterQ.value = "";
  debouncedSearch.cancel();
  void load({ resetPage: true });
}

function goToCreate() {
  if (!writeAllowed.value) return;
  void router.push({ name: "palestrante-detalhe" });
}

function pedirRemover(row: Palestrante) {
  if (!writeAllowed.value) return;
  pendingDelete.value = row;
}

async function confirmRemove() {
  const row = pendingDelete.value;
  pendingDelete.value = null;
  if (!row) return;
  success.value = null;
  error.value = null;
  try {
    await palestranteService.remove(row.id);
    await load({ resetPage: true });
    success.value = "Palestrante excluído.";
  } catch {
    error.value = "Erro ao excluir palestrante.";
  }
}

function onThumbError(event: Event) {
  const img = event.target as HTMLImageElement;
  img.style.display = "none";
}

onMounted(() => load());

onUnmounted(() => {
  debouncedSearch.cancel();
});
</script>

<template>
  <PageEnter>
  <div class="flex flex-col gap-6">
    <div class="flex flex-wrap items-center justify-between gap-4">
      <div>
        <h1 class="text-2xl font-semibold tracking-tight">Palestrantes</h1>
        <p class="mt-1 text-sm text-muted">
          Lista, busca e gerenciamento básico.
        </p>
      </div>
      <button
        v-if="writeAllowed"
        type="button"
        class="motion-press inline-flex items-center justify-center rounded-[length:var(--radius-control)] bg-accent px-4 py-2 text-sm font-medium text-white transition-transform hover:bg-accent-dark active:scale-[0.98]"
        @click="goToCreate"
      >
        Novo palestrante
      </button>
    </div>

    <p
      v-if="!writeAllowed"
      class="rounded-[length:var(--radius-control)] border border-line bg-surface px-4 py-3 text-sm text-muted"
      data-testid="readonly-message"
    >
      <template v-if="isLoggedIn">
        Perfil somente leitura — você pode consultar, mas não criar ou editar.
      </template>
      <template v-else>
        Faça login com perfil organizador para cadastrar ou editar palestrantes.
      </template>
    </p>

    <form
      class="flex flex-wrap items-end gap-3 rounded-[length:var(--radius-control)] border border-line bg-panel p-4"
      @submit.prevent="buscar"
    >
      <label class="flex w-full min-w-0 flex-1 flex-col gap-2 text-sm">
        <span class="font-medium">Buscar</span>
        <input
          v-model="filterQ"
          class="w-full rounded-[length:var(--radius-control)] border border-line bg-panel px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/20"
          placeholder="Digite para buscar"
        />
      </label>
      <button
        type="submit"
        class="inline-flex items-center justify-center rounded-[length:var(--radius-control)] bg-accent px-4 py-2 text-sm font-medium text-white hover:bg-accent-dark"
      >
        Buscar
      </button>
      <button
        type="button"
        class="inline-flex items-center justify-center rounded-[length:var(--radius-control)] border border-line bg-panel px-4 py-2 text-sm font-medium text-ink hover:bg-surface"
        @click="limparFiltro"
      >
        Limpar
      </button>
    </form>

    <AlertMotion
      :show="!!success"
      class="rounded-[length:var(--radius-control)] border border-line bg-accent-soft px-4 py-3 text-sm text-accent-dark"
    >
      {{ success }}
    </AlertMotion>

    <AlertMotion
      :show="!!error"
      class="rounded-[length:var(--radius-control)] border border-danger-border bg-danger-soft px-4 py-3 text-sm text-danger"
    >
      {{ error }}
    </AlertMotion>

    <LoadingSpinner :active="loading" variant="page" />

    <SkeletonShimmer v-if="loading" :rows="5" class="p-4" />

    <template v-if="!loading && items.length > 0">
      <div class="overflow-x-auto rounded-[length:var(--radius-control)] border border-line bg-panel">
        <table class="w-full text-sm">
          <thead>
            <tr class="border-b border-line bg-surface text-left text-muted">
              <th class="px-4 py-3 font-medium">Foto</th>
              <th class="px-4 py-3 font-medium">Nome</th>
              <th class="px-4 py-3 font-medium">E-mail</th>
              <th class="px-4 py-3 font-medium">Telefone</th>
              <th class="px-4 py-3 font-medium">Ações</th>
            </tr>
          </thead>
          <ListStagger
            tag="tbody"
            class="divide-y divide-line"
            :items-length="paged.items.length"
          >
            <tr
              v-for="(row, index) in paged.items"
              :key="row.id"
              class="hover:bg-surface"
              :style="{ '--motion-stagger-index': index }"
            >
              <td class="px-4 py-3">
                <img
                  v-if="isRemoteImageUrl(row.imagemURL)"
                  :src="row.imagemURL"
                  alt=""
                  class="h-10 w-10 rounded object-cover"
                  @error="onThumbError"
                />
                <span
                  v-else
                  class="text-xs text-muted"
                >—</span>
              </td>
              <td class="px-4 py-3 break-words font-medium">{{ row.nome }}</td>
              <td class="px-4 py-3">{{ row.email }}</td>
              <td class="px-4 py-3">{{ row.telefone }}</td>
              <td class="px-4 py-3">
                <div
                  v-if="writeAllowed"
                  class="flex flex-wrap gap-2"
                >
                  <router-link
                    :to="`/palestrantes/detalhes/${row.id}`"
                    class="inline-flex items-center justify-center rounded-[length:var(--radius-control)] border border-accent/30 bg-panel px-2 py-1 text-xs font-medium text-accent-dark hover:bg-accent-soft"
                  >
                    Editar
                  </router-link>
                  <button
                    type="button"
                    class="inline-flex items-center justify-center rounded-[length:var(--radius-control)] border border-danger-border bg-panel px-2 py-1 text-xs font-medium text-danger hover:bg-danger-soft"
                    @click="pedirRemover(row)"
                  >
                    Excluir
                  </button>
                </div>
                <span
                  v-else
                  class="text-xs text-muted"
                >—</span>
              </td>
            </tr>
          </ListStagger>
        </table>
      </div>

      <div
        v-if="paged.totalPages > 0"
        class="flex flex-wrap items-center justify-between gap-3"
      >
        <label class="flex items-center gap-2 text-sm">
          <span class="font-medium text-muted">Itens por página</span>
          <select
            v-model.number="pageSize"
            class="rounded-[length:var(--radius-control)] border border-line bg-panel px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/20"
            @change="onPageSizeChange"
          >
            <option
              v-for="size in PAGE_SIZES"
              :key="size"
              :value="size"
            >
              {{ size }}
            </option>
          </select>
        </label>
        <div class="flex flex-wrap items-center gap-3">
          <button
            type="button"
            class="inline-flex items-center justify-center rounded-[length:var(--radius-control)] border border-line bg-panel px-4 py-2 text-sm font-medium text-ink hover:bg-surface disabled:opacity-60"
            :disabled="paged.page <= 1"
            @click="goToPage(paged.page - 1)"
          >
            Anterior
          </button>
          <span class="text-sm text-muted">
            Página {{ paged.page }} de {{ paged.totalPages }}
          </span>
          <button
            type="button"
            class="inline-flex items-center justify-center rounded-[length:var(--radius-control)] border border-line bg-panel px-4 py-2 text-sm font-medium text-ink hover:bg-surface disabled:opacity-60"
            :disabled="paged.page >= paged.totalPages"
            @click="goToPage(paged.page + 1)"
          >
            Próxima
          </button>
        </div>
      </div>
    </template>

    <EmptyState
      :show="!loading && items.length === 0"
      class="rounded-[length:var(--radius-control)] border border-line bg-panel px-4 py-8 text-center text-sm text-muted"
    >
      Nenhum palestrante cadastrado.
    </EmptyState>

    <ConfirmDialog
      :open="pendingDelete !== null"
      title="Excluir palestrante"
      :message="deleteMessage"
      confirm-label="Excluir"
      @confirm="confirmRemove"
      @cancel="pendingDelete = null"
    />
  </div>
  </PageEnter>
</template>
