// Front/Front-React/src/components/user/PalestranteDetalhe.tsx
import { zodResolver } from "@hookform/resolvers/zod";
import { useEffect, useState } from "react";
import { useForm, type Resolver } from "react-hook-form";
import { FieldError } from "@/forms/components/FieldError";
import { LoadingSpinner } from "@/components/LoadingSpinner";
import {
  emptyPalestranteFormValues,
  palestranteSchema,
  type PalestranteFormValues,
} from "@/forms/schemas";
import type { Palestrante } from "@/models";
import { HttpError } from "@/services/http";
import { palestranteService } from "@/services/palestranteService";
import { AlertMotion } from "@/shared/motion";
import { apiErrorMessage } from "@/utils/apiErrorMessage";

const inputClass =
  "w-full rounded-[length:var(--radius-control)] border border-line bg-panel px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/20 disabled:cursor-not-allowed disabled:opacity-60";
const btnPrimary =
  "inline-flex items-center justify-center rounded-[length:var(--radius-control)] bg-accent px-4 py-2 text-sm font-medium text-white transition-transform hover:bg-accent-dark active:scale-[0.98] disabled:cursor-not-allowed disabled:opacity-60";

export function PalestranteDetalhe() {
  const [palestranteId, setPalestranteId] = useState<number | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [missingProfile, setMissingProfile] = useState(false);

  const {
    register,
    handleSubmit,
    reset,
    formState: { errors },
  } = useForm<PalestranteFormValues>({
    resolver: zodResolver(palestranteSchema) as Resolver<PalestranteFormValues>,
    defaultValues: emptyPalestranteFormValues(),
  });

  useEffect(() => {
    let cancelled = false;

    async function load() {
      setLoading(true);
      setError(null);
      setMissingProfile(false);

      try {
        const me = await palestranteService.getMe();
        if (cancelled) return;

        setPalestranteId(me.id);
        reset({
          nome: me.nome ?? "",
          email: me.email ?? "",
          telefone: me.telefone ?? "",
          imagemURL: me.imagemURL ?? "",
          miniCurriculo: me.miniCurriculo ?? "",
        });
      } catch (err) {
        if (cancelled) return;

        if (err instanceof HttpError && err.status === 404) {
          setMissingProfile(true);
          setPalestranteId(null);
          setError("Salve o perfil com função Palestrante primeiro");
          return;
        }

        if (err instanceof HttpError) {
          setError(apiErrorMessage(err.message, "Erro ao carregar palestrante."));
        } else {
          setError("Erro ao carregar palestrante.");
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    void load();

    return () => {
      cancelled = true;
    };
  }, [reset]);

  async function onSubmit(values: PalestranteFormValues) {
    if (palestranteId == null) return;

    setSaving(true);
    setError(null);
    setSuccess(null);

    const payload: Palestrante = {
      id: palestranteId,
      nome: values.nome,
      email: values.email,
      telefone: values.telefone,
      imagemURL: values.imagemURL,
      miniCurriculo: values.miniCurriculo,
    };

    try {
      await palestranteService.update(palestranteId, payload);
      setSuccess("Palestrante atualizado.");
    } catch (err) {
      if (err instanceof HttpError) {
        setError(apiErrorMessage(err.message, "Erro ao salvar palestrante."));
      } else {
        setError("Erro ao salvar palestrante.");
      }
    } finally {
      setSaving(false);
    }
  }

  const alertDangerClass =
    "rounded-[length:var(--radius-control)] border border-danger-border bg-danger-soft px-4 py-3 text-sm text-danger";
  const alertSuccessClass =
    "rounded-[length:var(--radius-control)] border border-line bg-surface px-4 py-3 text-sm text-accent-dark";

  if (loading) {
    return <p className="text-sm text-muted">Carregando detalhe palestrante…</p>;
  }

  return (
    <div className="flex flex-col gap-4">
      <AlertMotion show={!!error} className={alertDangerClass}>
        {error}
      </AlertMotion>
      <AlertMotion show={!!success} className={alertSuccessClass}>
        {success}
      </AlertMotion>

      <form
        onSubmit={handleSubmit(onSubmit)}
        className="flex flex-col gap-4"
        noValidate
      >
        <h2 className="border-b border-line pb-2 text-lg font-semibold">
          Detalhe Palestrante
        </h2>

        <label className="flex flex-col gap-2 text-sm">
          <span className="font-medium">Nome</span>
          <input className={inputClass} {...register("nome")} />
          <FieldError error={errors.nome} />
        </label>

        <label className="flex flex-col gap-2 text-sm">
          <span className="font-medium">E-mail</span>
          <input className={inputClass} type="email" {...register("email")} />
        </label>

        <label className="flex flex-col gap-2 text-sm">
          <span className="font-medium">Telefone</span>
          <input className={inputClass} {...register("telefone")} />
        </label>

        <label className="flex flex-col gap-2 text-sm">
          <span className="font-medium">URL da imagem</span>
          <input
            className={inputClass}
            type="url"
            placeholder="https://..."
            {...register("imagemURL")}
          />
        </label>

        <label className="flex flex-col gap-2 text-sm">
          <span className="font-medium">Mini currículo</span>
          <textarea className={inputClass} rows={3} {...register("miniCurriculo")} />
        </label>

        <div className="flex flex-col gap-3 border-t border-line pt-4 sm:flex-row sm:flex-wrap">
          <button
            type="submit"
            disabled={missingProfile || palestranteId == null || saving}
            className={`${btnPrimary} motion-press ml-auto w-full gap-2 sm:w-auto`}
          >
            <LoadingSpinner loading={saving} variant="button" />
            {saving ? "Salvando..." : "Salvar Alteração"}
          </button>
        </div>
      </form>
    </div>
  );
}

// Front/Front-Vue/src/components/user/perfil/PalestranteDetalhe.vue
<template>
  <div class="flex flex-col gap-4">
    <AlertMotion
      :show="!!error"
      class="rounded-[length:var(--radius-control)] border border-danger-border bg-danger-soft px-4 py-3 text-sm text-danger"
    >
      {{ error }}
    </AlertMotion>

    <AlertMotion
      :show="!!success"
      class="rounded-[length:var(--radius-control)] border border-line bg-surface px-4 py-3 text-sm text-accent-dark"
    >
      {{ success }}
    </AlertMotion>

    <p v-if="loading" class="text-sm text-muted">Carregando detalhe palestrante…</p>

    <form v-else class="flex flex-col gap-4" @submit.prevent="onSubmit">
      <h2 class="border-b border-line pb-2 text-lg font-semibold">Detalhe Palestrante</h2>

      <label class="flex flex-col gap-2 text-sm">
        <span class="font-medium">Nome</span>
        <input
          v-model="nome"
          v-bind="nomeAttrs"
          name="nome"
          type="text"
          class="w-full rounded-[length:var(--radius-control)] border border-line bg-panel px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/20"
        />
        <span v-if="errors.nome" class="text-xs text-danger">{{ errors.nome }}</span>
      </label>

      <label class="flex flex-col gap-2 text-sm">
        <span class="font-medium">E-mail</span>
        <input
          v-model="email"
          v-bind="emailAttrs"
          name="email"
          type="email"
          class="w-full rounded-[length:var(--radius-control)] border border-line bg-panel px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/20"
        />
      </label>

      <label class="flex flex-col gap-2 text-sm">
        <span class="font-medium">Telefone</span>
        <input
          v-model="telefone"
          v-bind="telefoneAttrs"
          name="telefone"
          type="text"
          class="w-full rounded-[length:var(--radius-control)] border border-line bg-panel px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/20"
        />
      </label>

      <label class="flex flex-col gap-2 text-sm">
        <span class="font-medium">URL da imagem</span>
        <input
          v-model="imagemURL"
          v-bind="imagemURLAttrs"
          name="imagemURL"
          type="url"
          placeholder="https://..."
          class="w-full rounded-[length:var(--radius-control)] border border-line bg-panel px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/20"
        />
      </label>

      <label class="flex flex-col gap-2 text-sm">
        <span class="font-medium">Mini currículo</span>
        <textarea
          v-model="miniCurriculo"
          v-bind="miniCurriculoAttrs"
          name="miniCurriculo"
          rows="3"
          class="w-full rounded-[length:var(--radius-control)] border border-line bg-panel px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/20"
        />
      </label>

      <div class="flex flex-col gap-3 border-t border-line pt-4 sm:flex-row sm:flex-wrap">
        <button
          type="submit"
          class="motion-press inline-flex w-full items-center justify-center gap-2 rounded-[length:var(--radius-control)] bg-accent px-4 py-2 text-sm font-medium text-white hover:bg-accent-dark active:scale-[0.98] disabled:cursor-not-allowed disabled:opacity-60 sm:ml-auto sm:w-auto"
          :disabled="missingProfile || palestranteId == null || saving"
        >
          {{ saving ? "Salvando..." : "Salvar Alteração" }}
        </button>
      </div>
    </form>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useForm } from "vee-validate";
import { isAxiosError } from "axios";
import palestranteService from "../../../services/palestranteService";
import {
  defaultPalestranteFormValues,
  palestranteSchema,
  type PalestranteFormValues,
} from "../../../forms/schemas";
import { toTypedSchema } from "../../../forms/toTyped";
import AlertMotion from "../../../shared/motion/AlertMotion.vue";
import { apiErrorMessage } from "../../../utils/apiErrorMessage";

const palestranteId = ref<number | null>(null);
const loading = ref(true);
const saving = ref(false);
const error = ref<string | null>(null);
const success = ref<string | null>(null);
const missingProfile = ref(false);

const { defineField, handleSubmit, errors, setValues } = useForm({
  validationSchema: toTypedSchema(palestranteSchema),
  initialValues: defaultPalestranteFormValues(),
});

const [nome, nomeAttrs] = defineField("nome");
const [email, emailAttrs] = defineField("email");
const [telefone, telefoneAttrs] = defineField("telefone");
const [imagemURL, imagemURLAttrs] = defineField("imagemURL");
const [miniCurriculo, miniCurriculoAttrs] = defineField("miniCurriculo");

async function load() {
  loading.value = true;
  error.value = null;
  missingProfile.value = false;
  try {
    const { data } = await palestranteService.getMe();
    palestranteId.value = data.id;
    setValues({
      nome: data.nome ?? "",
      email: data.email ?? "",
      telefone: data.telefone ?? "",
      imagemURL: data.imagemURL ?? "",
      miniCurriculo: data.miniCurriculo ?? "",
    });
  } catch (err) {
    if (isAxiosError(err) && err.response?.status === 404) {
      missingProfile.value = true;
      error.value = "Salve o perfil com função Palestrante primeiro";
      palestranteId.value = null;
    } else if (isAxiosError(err)) {
      error.value = apiErrorMessage(err.response?.data, "Erro ao carregar palestrante.");
    } else {
      error.value = "Erro ao carregar palestrante.";
    }
  } finally {
    loading.value = false;
  }
}

const onSubmit = handleSubmit(async (formValues: PalestranteFormValues) => {
  if (palestranteId.value == null) return;

  saving.value = true;
  error.value = null;
  success.value = null;
  try {
    await palestranteService.update(palestranteId.value, formValues);
    success.value = "Palestrante atualizado.";
  } catch (err) {
    if (isAxiosError(err)) {
      error.value = apiErrorMessage(err.response?.data, "Erro ao salvar palestrante.");
    } else {
      error.value = "Erro ao salvar palestrante.";
    }
  } finally {
    saving.value = false;
  }
});

onMounted(() => {
  void load();
});
</script>
