// Front/Front-React/src/shared/motion/ModalMotion.tsx
import { AnimatePresence, motion } from "motion/react";
import type { ReactNode } from "react";
import { usePrefersReducedMotion } from "./usePrefersReducedMotion";

type Props = {
  open: boolean;
  onCancel: () => void;
  children: ReactNode;
};

export function ModalMotion({ open, onCancel, children }: Props) {
  const reduced = usePrefersReducedMotion();
  return (
    <AnimatePresence>
      {open ? (
        <motion.div
          className="fixed inset-0 z-50 flex items-center justify-center bg-ink/40 p-4"
          role="presentation"
          onClick={onCancel}
          initial={reduced ? false : { opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={reduced ? undefined : { opacity: 0 }}
          transition={{ duration: reduced ? 0 : 0.32 }}
        >
          <motion.div
            role="presentation"
            onClick={(e) => e.stopPropagation()}
            initial={reduced ? false : { opacity: 0, scale: 0.98 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={reduced ? undefined : { opacity: 0, scale: 0.98 }}
            transition={{
              duration: reduced ? 0 : 0.32,
              ease: [0.16, 1, 0.3, 1],
            }}
          >
            {children}
          </motion.div>
        </motion.div>
      ) : null}
    </AnimatePresence>
  );
}

// Front/Front-Vue/src/shared/motion/ModalMotion.vue
<template>
  <Transition :name="reduced ? undefined : 'motion-modal-backdrop'">
    <div
      v-if="open"
      class="fixed inset-0 z-50 flex items-center justify-center bg-ink/40 p-4"
      role="presentation"
      @click="$emit('cancel')"
    >
      <Transition appear :name="reduced ? undefined : 'motion-modal-panel'">
        <div @click.stop>
          <slot />
        </div>
      </Transition>
    </div>
  </Transition>
</template>

<script setup lang="ts">
import { usePrefersReducedMotion } from "./usePrefersReducedMotion";

defineProps<{ open: boolean }>();
defineEmits<{ cancel: [] }>();
const reduced = usePrefersReducedMotion();
</script>
