// Front/Front-Vue/src/components/user/perfil/RedesSociais.vue
<template>
  <div class="flex flex-col gap-4">
    <div class="flex items-center justify-between">
      <h3 class="text-lg font-semibold">Redes sociais</h3>
      <button
        type="button"
        class="inline-flex items-center justify-center rounded-[length:var(--radius-control)] border border-accent/30 bg-panel px-2 py-1 text-xs font-medium text-accent-dark hover:bg-accent-soft"
        @click="addRede"
      >
        + Rede
      </button>
    </div>

    <AlertMotion
      :show="!!redesError"
      class="rounded-[length:var(--radius-control)] border border-danger-border bg-danger-soft px-3 py-2 text-sm text-danger"
    >
      {{ redesError }}
    </AlertMotion>
    <AlertMotion
      :show="!!redesSuccess"
      class="rounded-[length:var(--radius-control)] border border-line bg-surface px-3 py-2 text-sm text-accent-dark"
    >
      {{ redesSuccess }}
    </AlertMotion>

    <LoadingSpinner :active="redesLoading" variant="inline" label="Carregando redes..." />

    <div class="flex flex-col gap-2">
      <div
        v-for="(rede, index) in redes"
        :key="index"
        class="grid gap-2 rounded-[length:var(--radius-control)] border border-line bg-surface p-3 md:grid-cols-[1fr_1fr_auto]"
      >
        <input
          v-model="rede.nome"
          class="w-full rounded-[length:var(--radius-control)] border border-line bg-panel px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/20"
          placeholder="Nome"
        />
        <input
          v-model="rede.url"
          class="w-full rounded-[length:var(--radius-control)] border border-line bg-panel px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/20"
          placeholder="URL"
        />
        <button
          type="button"
          class="inline-flex items-center justify-center rounded-[length:var(--radius-control)] border border-danger-border bg-panel px-2 py-1 text-xs font-medium text-danger hover:bg-danger-soft"
          @click="askDeleteRede(index)"
        >
          Excluir
        </button>
      </div>
    </div>

    <div class="flex justify-end">
      <button
        type="button"
        :disabled="savingRedes || redesLoading"
        class="inline-flex items-center justify-center gap-2 rounded-[length:var(--radius-control)] bg-accent px-4 py-2 text-sm font-medium text-white disabled:cursor-not-allowed disabled:opacity-60"
        @click="saveRedes"
      >
        <LoadingSpinner :active="savingRedes" variant="button" />
        {{ savingRedes ? "Salvando..." : "Salvar Redes" }}
      </button>
    </div>

    <ConfirmDialog
      :open="pendingRedeDelete !== null"
      title="Excluir rede social"
      :message="deleteRedeMessage"
      confirm-label="Excluir"
      @confirm="confirmDeleteRede"
      @cancel="pendingRedeDelete = null"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { isAxiosError } from "axios";
import redeSocialService, {
  type RedeSocialPayload,
} from "../../../services/redeSocialService";
import LoadingSpinner from "../../common/LoadingSpinner.vue";
import ConfirmDialog from "../../../shared/ConfirmDialog.vue";
import AlertMotion from "../../../shared/motion/AlertMotion.vue";
import { redeSocialFormSchema } from "../../../forms/schemas/eventoSchema";
import { apiErrorMessage } from "../../../utils/apiErrorMessage";

const redesLoading = ref(false);
const savingRedes = ref(false);
const redesError = ref<string | null>(null);
const redesSuccess = ref<string | null>(null);
const redes = ref<RedeSocialPayload[]>([]);
const pendingRedeDelete = ref<number | null>(null);

const deleteRedeMessage = computed(() => {
  if (pendingRedeDelete.value === null) return "";
  const rede = redes.value[pendingRedeDelete.value];
  return `Deseja excluir a rede "${rede?.nome || "esta rede"}"?`;
});

function emptyRede(): RedeSocialPayload {
  return { id: 0, nome: "", url: "" };
}

function addRede() {
  redes.value.push(emptyRede());
}

function askDeleteRede(index: number) {
  pendingRedeDelete.value = index;
}

async function confirmDeleteRede() {
  const index = pendingRedeDelete.value;
  pendingRedeDelete.value = null;
  if (index === null) return;

  const rede = redes.value[index];
  if (!rede) return;

  redesError.value = null;
  redesSuccess.value = null;

  try {
    if (rede.id && rede.id > 0) {
      await redeSocialService.removeMine(rede.id);
    }
    redes.value.splice(index, 1);
    redesSuccess.value = "Rede social excluída.";
  } catch {
    redesError.value = "Erro ao excluir rede social.";
  }
}

function validateRedes(): boolean {
  for (const rede of redes.value) {
    const result = redeSocialFormSchema.safeParse(rede);
    if (!result.success) {
      redesError.value = "Preencha nome e URL de todas as redes.";
      return false;
    }
  }
  return true;
}

async function loadRedes() {
  redesLoading.value = true;
  redesError.value = null;
  try {
    const { data } = await redeSocialService.listMine();
    redes.value = data.map((rede) => ({
      id: rede.id ?? 0,
      nome: rede.nome,
      url: rede.url,
    }));
  } catch {
    redesError.value = "Não foi possível carregar redes sociais.";
  } finally {
    redesLoading.value = false;
  }
}

async function saveRedes() {
  if (!validateRedes()) return;

  savingRedes.value = true;
  redesError.value = null;
  redesSuccess.value = null;

  try {
    const { data } = await redeSocialService.saveMine(redes.value);
    redes.value = data.map((rede: RedeSocialPayload) => ({
      id: rede.id ?? 0,
      nome: rede.nome,
      url: rede.url,
    }));
    redesSuccess.value = "Redes sociais salvas com sucesso.";
  } catch (err) {
    if (isAxiosError(err)) {
      redesError.value = apiErrorMessage(
        err.response?.data,
        "Erro ao salvar redes sociais.",
      );
    } else {
      redesError.value = "Erro ao salvar redes sociais.";
    }
  } finally {
    savingRedes.value = false;
  }
}

onMounted(() => {
  void loadRedes();
});
</script>

// Front/Front-Angular/src/app/components/user/profile/redes-sociais/redes-sociais.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { FormArray, FormBuilder, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { LoadingSpinnerComponent } from '../../../common/loading-spinner/loading-spinner.component';
import { ConfirmDialogComponent } from '../../../../shared/confirm-dialog/confirm-dialog.component';
import { apiErrorMessage } from '../../../../shared/api-error-message';
import { createRedeGroup } from '../../../../forms/schemas/evento-form.factory';
import { RedeSocial } from '../../../../models';
import { RedeSocialService } from '../../../../services/rede-social.service';
import { alertAnimation, SkeletonShimmerComponent } from '../../../../shared/motion';

@Component({
  selector: 'app-redes-sociais',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    LoadingSpinnerComponent,
    ConfirmDialogComponent,
    SkeletonShimmerComponent,
  ],
  templateUrl: './redes-sociais.component.html',
  animations: [alertAnimation],
})
export class RedesSociaisComponent implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly redeSocialService = inject(RedeSocialService);

  redesForm = this.fb.group({
    redes: this.fb.array<FormGroup>([]),
  });

  loading = false;
  saving = false;
  error: string | null = null;
  success: string | null = null;
  pendingRedeDelete: number | null = null;

  get redes(): FormArray<FormGroup> {
    return this.redesForm.get('redes') as FormArray<FormGroup>;
  }

  get deleteRedeMessage(): string {
    if (this.pendingRedeDelete === null) return '';
    const nome = this.redes.at(this.pendingRedeDelete)?.get('nome')?.value || 'esta rede';
    return `Deseja excluir a rede "${nome}"?`;
  }

  ngOnInit(): void {
    this.loadRedes();
  }

  addRede(): void {
    this.redes.push(createRedeGroup(this.fb, 0));
  }

  askDeleteRede(index: number): void {
    this.pendingRedeDelete = index;
  }

  cancelDeleteRede(): void {
    this.pendingRedeDelete = null;
  }

  confirmDeleteRede(): void {
    const index = this.pendingRedeDelete;
    this.pendingRedeDelete = null;
    if (index === null) return;
    this.deleteRedeAt(index);
  }

  saveRedes(): void {
    this.redesForm.updateValueAndValidity();
    if (this.redesForm.invalid) {
      this.redes.markAllAsTouched();
      return;
    }

    this.saving = true;
    this.error = null;
    this.success = null;

    const redes = this.redes.getRawValue() as RedeSocial[];
    this.redeSocialService.saveMine(redes).subscribe({
      next: (saved) => {
        this.setRedes(saved);
        this.success = 'Redes sociais salvas com sucesso.';
        this.saving = false;
      },
      error: (err) => {
        this.error = apiErrorMessage(err.error, 'Erro ao salvar redes sociais.');
        this.saving = false;
      },
    });
  }

  private loadRedes(): void {
    this.loading = true;
    this.error = null;
    this.redeSocialService.getMine().subscribe({
      next: (redes) => {
        this.setRedes(redes);
        this.loading = false;
      },
      error: () => {
        this.error = 'Não foi possível carregar redes sociais.';
        this.loading = false;
      },
    });
  }

  private deleteRedeAt(index: number): void {
    const group = this.redes.at(index);
    if (!group) return;

    const redeId = Number(group.get('id')?.value ?? 0);

    if (redeId > 0) {
      this.redeSocialService.deleteMine(redeId).subscribe({
        next: () => {
          this.redes.removeAt(index);
          this.success = 'Rede social excluída.';
        },
        error: () => {
          this.error = 'Erro ao excluir rede social.';
        },
      });
      return;
    }

    this.redes.removeAt(index);
    this.success = 'Rede social removida.';
  }

  private setRedes(redes: RedeSocial[]): void {
    const array = this.fb.array(
      redes.map((rede) => {
        const group = createRedeGroup(this.fb, 0);
        group.patchValue({
          id: rede.id,
          nome: rede.nome,
          url: rede.url,
          eventoId: 0,
        });
        return group;
      }),
    );
    this.redesForm.setControl('redes', array);
  }
}

<div class="flex flex-col gap-4">
  <div class="flex items-center justify-between">
    <h2 class="text-lg font-semibold">Redes sociais</h2>
    <button
      type="button"
      class="inline-flex items-center justify-center rounded-[length:var(--radius-control)] border border-accent/30 bg-panel px-2 py-1 text-xs font-medium text-accent-dark hover:bg-accent-soft"
      (click)="addRede()"
    >
      + Rede
    </button>
  </div>

  @if (error) {
    <p
      [@alertMotion]
      class="rounded-[length:var(--radius-control)] border border-danger-border bg-danger-soft px-3 py-2 text-sm text-danger"
    >
      {{ error }}
    </p>
  }
  @if (success) {
    <p
      [@alertMotion]
      class="rounded-[length:var(--radius-control)] border border-line bg-surface px-3 py-2 text-sm text-accent-dark"
    >
      {{ success }}
    </p>
  }

  <app-loading-spinner
    [active]="loading"
    variant="inline"
    label="Carregando redes..."
  />

  @if (loading) {
    <app-skeleton-shimmer [rows]="3" />
  } @else {
    <div [formGroup]="redesForm">
      <div formArrayName="redes" class="flex flex-col gap-2">
        @for (rede of redes.controls; track $index) {
          <div
            class="grid gap-2 rounded-[length:var(--radius-control)] border border-line bg-surface p-3 md:grid-cols-[1fr_1fr_auto]"
            [formGroupName]="$index"
          >
            <div class="flex flex-col gap-1">
              <input
                class="w-full rounded-[length:var(--radius-control)] border border-line bg-panel px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/20"
                formControlName="nome"
                placeholder="Nome"
              />
              @if (rede.get('nome')?.invalid && rede.get('nome')?.touched) {
                <span class="text-xs text-danger">Nome é obrigatório.</span>
              }
            </div>
            <div class="flex flex-col gap-1">
              <input
                class="w-full rounded-[length:var(--radius-control)] border border-line bg-panel px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/20"
                formControlName="url"
                placeholder="URL"
              />
              @if (rede.get('url')?.invalid && rede.get('url')?.touched) {
                <span class="text-xs text-danger">URL é obrigatória.</span>
              }
            </div>
            <button
              type="button"
              class="inline-flex items-center justify-center rounded-[length:var(--radius-control)] border border-danger-border bg-panel px-2 py-1 text-xs font-medium text-danger hover:bg-danger-soft"
              (click)="askDeleteRede($index)"
            >
              Excluir
            </button>
          </div>
        }
      </div>
    </div>
  }

  <div class="flex justify-end">
    <button
      type="button"
      class="motion-press inline-flex items-center justify-center gap-2 rounded-[length:var(--radius-control)] bg-accent px-4 py-2 text-sm font-medium text-white hover:bg-accent-dark active:scale-[0.98] disabled:cursor-not-allowed disabled:opacity-60"
      [disabled]="saving || loading"
      (click)="saveRedes()"
    >
      <app-loading-spinner [active]="saving" variant="button" />
      {{ saving ? 'Salvando...' : 'Salvar Redes' }}
    </button>
  </div>
</div>

<app-confirm-dialog
  [open]="pendingRedeDelete !== null"
  title="Excluir rede social"
  [message]="deleteRedeMessage"
  confirmLabel="Excluir"
  (confirm)="confirmDeleteRede()"
  (cancel)="cancelDeleteRede()"
/>
