// Front/Front-Angular/src/app/components/user/login/login.component.ts
import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AccountService } from '../../../services/account.service';
import { apiErrorMessage } from '../../../shared/api-error-message';

@Component({
  selector: 'app-login',
  imports: [ReactiveFormsModule, RouterLink],
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss',
})
export class LoginComponent {
  private readonly fb = inject(FormBuilder);
  private readonly accountService = inject(AccountService);
  private readonly router = inject(Router);

  form = this.fb.group({
    userName: ['', Validators.required],
    password: ['', Validators.required],
  });

  saving = false;
  error: string | null = null;

  submit(): void {
    this.form.updateValueAndValidity();
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.saving = true;
    this.error = null;

    this.accountService.login(this.form.getRawValue() as { userName: string; password: string }).subscribe({
      next: () => {
        this.saving = false;
        this.router.navigate(['/eventos']);
      },
      error: (err) => {
        this.error = apiErrorMessage(err.error, 'Usuário ou senha inválidos.');
        this.saving = false;
      },
    });
  }
}

<section [@pageEnter] class="mx-auto flex w-full min-w-0 max-w-md flex-col gap-6">
  <div>
    <h1 class="text-2xl font-semibold tracking-tight">Login</h1>
    <p class="mt-1 text-sm text-muted">Entre com seu usuário e senha para manter eventos e palestrantes.</p>
  </div>

  @if (error) {
    <p
      [@alertMotion]
      class="rounded-[length:var(--radius-control)] border border-danger-border bg-danger-soft px-4 py-3 text-sm text-danger"
    >
      {{ error }}
    </p>
  }

  <form
    [@panelEnter]
    class="flex flex-col gap-4 rounded-[length:var(--radius-control)] border border-line bg-panel p-6"
    [formGroup]="form"
    (ngSubmit)="submit()"
  >
    <label class="flex flex-col gap-2 text-sm">
      <span class="font-medium">Usuário</span>
      <input
        type="text"
        formControlName="userName"
        class="w-full rounded-[length:var(--radius-control)] border border-line bg-panel px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/20"
        placeholder="seu.usuario"
        autocomplete="username"
      />
      @if (form.get('userName')?.invalid && form.get('userName')?.touched) {
        <span class="text-xs text-danger">Usuário é obrigatório.</span>
      }
    </label>
    <label class="flex flex-col gap-2 text-sm">
      <span class="font-medium">Senha</span>
      <input
        type="password"
        formControlName="password"
        class="w-full rounded-[length:var(--radius-control)] border border-line bg-panel px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/20"
        placeholder="••••••••"
        autocomplete="current-password"
      />
      @if (form.get('password')?.invalid && form.get('password')?.touched) {
        <span class="text-xs text-danger">Senha é obrigatória.</span>
      }
    </label>
    <button
      type="submit"
      class="motion-press inline-flex w-full items-center justify-center gap-2 rounded-[length:var(--radius-control)] bg-accent px-4 py-2 text-sm font-medium text-white hover:bg-accent-dark active:scale-[0.98] disabled:cursor-not-allowed disabled:opacity-60"
      [disabled]="saving"
    >
      <app-loading-spinner [active]="saving" variant="button" />
      {{ saving ? 'Entrando...' : 'Entrar' }}
    </button>
  </form>

  <p class="text-center text-sm text-muted">
    Não tem conta?
    <a routerLink="/register" class="font-medium text-accent-dark hover:underline">Cadastre-se</a>
  </p>
</section>

// Front/Front-Vue/src/components/user/login/LoginComponent.vue
<template>
  <PageEnter>
    <div class="mx-auto flex w-full min-w-0 max-w-md flex-col gap-6">
      <div>
        <h1 class="text-2xl font-semibold tracking-tight">Login</h1>
        <p class="mt-1 text-sm text-muted">
          Entre com seu usuário para editar eventos e gerenciar seu perfil.
        </p>
      </div>

      <AlertMotion
        :show="!!error"
        class="rounded-[length:var(--radius-control)] border border-danger-border bg-danger-soft px-4 py-3 text-sm text-danger"
      >
        {{ error }}
      </AlertMotion>

      <form
        class="flex flex-col gap-4 rounded-[length:var(--radius-control)] border border-line bg-panel p-6"
        @submit.prevent="submitForm"
      >
        <label class="flex flex-col gap-2 text-sm">
          <span class="font-medium">Usuário</span>
          <input
            v-model="userName"
            v-bind="userNameAttrs"
            autocomplete="username"
            class="w-full rounded-[length:var(--radius-control)] border border-line bg-panel px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/20"
          />
          <span v-if="errors.userName" class="text-xs text-danger">{{ errors.userName }}</span>
        </label>
        <label class="flex flex-col gap-2 text-sm">
          <span class="font-medium">Senha</span>
          <input
            v-model="password"
            v-bind="passwordAttrs"
            type="password"
            autocomplete="current-password"
            class="w-full rounded-[length:var(--radius-control)] border border-line bg-panel px-3 py-2 text-sm outline-none focus:border-accent focus:ring-2 focus:ring-accent/20"
          />
          <span v-if="errors.password" class="text-xs text-danger">{{ errors.password }}</span>
        </label>
        <button
          type="submit"
          :disabled="submitting"
          class="motion-press inline-flex w-full items-center justify-center gap-2 rounded-[length:var(--radius-control)] bg-accent px-4 py-2 text-sm font-medium text-white disabled:cursor-not-allowed disabled:opacity-60"
        >
          <LoadingSpinner :active="submitting" variant="button" />
          {{ submitting ? "Entrando..." : "Entrar" }}
        </button>
      </form>

      <p class="text-center text-sm text-muted">
        Não tem conta?
        <router-link to="/user/registro" class="font-medium text-accent-dark hover:underline">
          Cadastre-se
        </router-link>
      </p>
    </div>
  </PageEnter>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { useRoute, useRouter } from "vue-router";
import { useForm } from "vee-validate";
import { toTypedSchema } from "@vee-validate/zod";
import { z } from "zod";
import accountService from "../../../services/accountService";
import LoadingSpinner from "../../common/LoadingSpinner.vue";
import { isAxiosError } from "axios";
import { apiErrorMessage } from "../../../utils/apiErrorMessage";
import PageEnter from "../../../shared/motion/PageEnter.vue";
import AlertMotion from "../../../shared/motion/AlertMotion.vue";

const loginSchema = z.object({
  userName: z.string().trim().min(1, "Usuário é obrigatório"),
  password: z.string().min(1, "Senha é obrigatória"),
});

const router = useRouter();
const route = useRoute();
const error = ref<string | null>(null);
const submitting = ref(false);

const { defineField, handleSubmit, errors } = useForm({
  validationSchema: toTypedSchema(loginSchema),
  initialValues: { userName: "", password: "" },
});

const [userName, userNameAttrs] = defineField("userName");
const [password, passwordAttrs] = defineField("password");

const submitForm = handleSubmit(async (values) => {
  submitting.value = true;
  error.value = null;

  try {
    await accountService.login(values);
    const redirect = typeof route.query.redirect === "string" ? route.query.redirect : "/eventos/lista";
    await router.push(redirect);
  } catch (err) {
    if (isAxiosError(err) && err.response?.status === 401) {
      error.value = apiErrorMessage(
        err.response?.data,
        "Usuário ou senha inválidos.",
      );
    } else {
      error.value = "Não foi possível entrar. Tente novamente.";
    }
  } finally {
    submitting.value = false;
  }
});
</script>
