// Front/Front-Vue/src/shared/motion/EmptyState.vue
<template>
  <Transition :name="reduced ? undefined : 'motion-empty'">
    <div v-if="show" :class="className"><slot /></div>
  </Transition>
</template>

<script setup lang="ts">
import { usePrefersReducedMotion } from "./usePrefersReducedMotion";

defineProps<{ show: boolean; className?: string }>();
const reduced = usePrefersReducedMotion();
</script>

// Front/Front-React/src/shared/motion/EmptyState.tsx
import { AnimatePresence, motion } from "motion/react";
import type { ReactNode } from "react";
import { usePrefersReducedMotion } from "./usePrefersReducedMotion";

type Props = { show: boolean; children: ReactNode; className?: string };

export function EmptyState({ show, children, className }: Props) {
  const reduced = usePrefersReducedMotion();
  return (
    <AnimatePresence>
      {show ? (
        <motion.div
          className={className}
          initial={reduced ? false : { opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={reduced ? undefined : { opacity: 0 }}
          transition={{ duration: reduced ? 0 : 0.22 }}
        >
          {children}
        </motion.div>
      ) : null}
    </AnimatePresence>
  );
}
