// Front/Front-Vue/src/shared/motion/SkeletonShimmer.vue
<template>
  <div class="flex flex-col gap-3" aria-hidden="true">
    <div
      v-for="i in rows"
      :key="i"
      :class="
        reduced
          ? 'h-10 rounded-[length:var(--radius-control)] bg-line'
          : 'motion-skeleton h-10 rounded-[length:var(--radius-control)]'
      "
    />
  </div>
</template>

<script setup lang="ts">
import { usePrefersReducedMotion } from "./usePrefersReducedMotion";

withDefaults(defineProps<{ rows?: number }>(), { rows: 4 });
const reduced = usePrefersReducedMotion();
</script>

// Front/Front-React/src/shared/motion/SkeletonShimmer.tsx
import { usePrefersReducedMotion } from "./usePrefersReducedMotion";

type Props = { rows?: number; className?: string };

export function SkeletonShimmer({ rows = 4, className }: Props) {
  const reduced = usePrefersReducedMotion();
  return (
    <div className={className ?? "flex flex-col gap-3"} aria-hidden="true">
      {Array.from({ length: rows }, (_, i) => (
        <div
          key={i}
          className={
            reduced
              ? "h-10 rounded-[length:var(--radius-control)] bg-line"
              : "motion-skeleton h-10 rounded-[length:var(--radius-control)]"
          }
        />
      ))}
    </div>
  );
}
