// Front/Front-React/src/shared/Nav.tsx
import { useEffect, useState } from "react";
import { NavLink, useLocation, useNavigate } from "react-router-dom";
import { accountService } from "@/services/accountService";
import { isAuthenticated } from "@/services/authToken";

const linkClass = ({ isActive }: { isActive: boolean }) =>
  [
    "rounded-[length:var(--radius-control)] px-3 py-2 text-sm font-medium transition-colors",
    isActive
      ? "bg-accent-soft text-accent-dark"
      : "text-muted hover:bg-accent-soft hover:text-accent-dark",
  ].join(" ");

const logoutClass =
  "rounded-[length:var(--radius-control)] px-3 py-2 text-sm font-medium text-muted transition-colors hover:bg-accent-soft hover:text-accent-dark";

function NavLinks({ onNavigate }: { onNavigate?: () => void }) {
  const navigate = useNavigate();
  const loggedIn = isAuthenticated();

  function handleLogout() {
    accountService.logout();
    onNavigate?.();
    void navigate("/login");
  }

  return (
    <>
      <NavLink to="/eventos" className={linkClass} onClick={onNavigate}>
        Eventos
      </NavLink>
      <NavLink to="/palestrantes" className={linkClass} onClick={onNavigate}>
        Palestrantes
      </NavLink>
      {loggedIn ? (
        <>
          <NavLink to="/perfil" className={linkClass} onClick={onNavigate}>
            Perfil
          </NavLink>
          <button type="button" onClick={handleLogout} className={logoutClass}>
            Sair
          </button>
        </>
      ) : (
        <>
          <NavLink to="/login" className={linkClass} onClick={onNavigate}>
            Login
          </NavLink>
          <NavLink to="/register" className={linkClass} onClick={onNavigate}>
            Cadastro
          </NavLink>
        </>
      )}
    </>
  );
}

export function Nav() {
  const location = useLocation();
  const [menuOpen, setMenuOpen] = useState(false);

  useEffect(() => {
    setMenuOpen(false);
  }, [location.pathname]);

  return (
    <header className="sticky top-0 z-10 border-b border-line bg-panel">
      <div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-3">
        <NavLink
          to="/eventos"
          className="text-xl font-semibold text-accent-dark"
        >
          ProEventos React
        </NavLink>

        <button
          type="button"
          className="rounded-[length:var(--radius-control)] p-2 text-muted transition-colors hover:bg-accent-soft hover:text-accent-dark md:hidden"
          aria-expanded={menuOpen}
          aria-controls="mobile-nav"
          aria-label="Menu"
          onClick={() => setMenuOpen((open) => !open)}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="size-6"
            aria-hidden="true"
          >
            {menuOpen ? (
              <>
                <line x1="18" y1="6" x2="6" y2="18" />
                <line x1="6" y1="6" x2="18" y2="18" />
              </>
            ) : (
              <>
                <line x1="3" y1="6" x2="21" y2="6" />
                <line x1="3" y1="12" x2="21" y2="12" />
                <line x1="3" y1="18" x2="21" y2="18" />
              </>
            )}
          </svg>
        </button>

        <nav className="hidden flex-wrap gap-1 md:flex">
          <NavLinks />
        </nav>
      </div>

      {menuOpen && (
        <nav
          id="mobile-nav"
          className="flex flex-col gap-1 border-t border-line px-4 py-3 md:hidden"
        >
          <NavLinks onNavigate={() => setMenuOpen(false)} />
        </nav>
      )}
    </header>
  );
}

// Front/Front-Angular/src/app/shared/nav/nav.component.ts
import { Component, inject } from '@angular/core';
import { Router, RouterLink, RouterLinkActive } from '@angular/router';
import { AccountService } from '../../services/account.service';
import { AuthTokenService } from '../../services/auth-token.service';

@Component({
  selector: 'app-nav',
  imports: [RouterLink, RouterLinkActive],
  templateUrl: './nav.component.html',
  styleUrl: './nav.component.scss',
})
export class NavComponent {
  private readonly authToken = inject(AuthTokenService);
  private readonly accountService = inject(AccountService);
  private readonly router = inject(Router);

  get isLoggedIn(): boolean {
    return this.authToken.isAuthenticated();
  }

  logout(): void {
    this.accountService.logout();
    this.router.navigate(['/login']);
  }
}

<header class="sticky top-0 z-10 border-b border-line bg-panel">
  <div class="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-3">
    <a routerLink="/eventos" class="text-xl font-semibold text-accent-dark" (click)="closeMenu()">
      ProEventos Angular
    </a>

    <button
      type="button"
      class="inline-flex items-center justify-center rounded-[length:var(--radius-control)] p-2 text-muted transition-colors hover:bg-accent-soft hover:text-accent-dark md:hidden"
      (click)="toggleMenu()"
      [attr.aria-expanded]="menuOpen"
      aria-controls="mobile-nav"
      [attr.aria-label]="menuOpen ? 'Fechar menu' : 'Abrir menu'"
    >
      @if (menuOpen) {
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="size-6"
          aria-hidden="true"
        >
          <path d="M18 6 6 18" />
          <path d="m6 6 12 12" />
        </svg>
      } @else {
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          stroke-linejoin="round"
          class="size-6"
          aria-hidden="true"
        >
          <path d="M4 6h16" />
          <path d="M4 12h16" />
          <path d="M4 18h16" />
        </svg>
      }
    </button>

    <nav class="hidden flex-wrap gap-1 md:flex">
      <a
        routerLink="/eventos"
        routerLinkActive="bg-accent-soft text-accent-dark"
        [routerLinkActiveOptions]="{ exact: false }"
        class="rounded-[length:var(--radius-control)] px-3 py-2 text-sm font-medium text-muted transition-colors hover:bg-accent-soft hover:text-accent-dark"
      >
        Eventos
      </a>
      <a
        routerLink="/palestrantes"
        routerLinkActive="bg-accent-soft text-accent-dark"
        class="rounded-[length:var(--radius-control)] px-3 py-2 text-sm font-medium text-muted transition-colors hover:bg-accent-soft hover:text-accent-dark"
      >
        Palestrantes
      </a>
      @if (isLoggedIn) {
        <a
          routerLink="/perfil"
          routerLinkActive="bg-accent-soft text-accent-dark"
          class="rounded-[length:var(--radius-control)] px-3 py-2 text-sm font-medium text-muted transition-colors hover:bg-accent-soft hover:text-accent-dark"
        >
          Perfil
        </a>
        <button
          type="button"
          class="rounded-[length:var(--radius-control)] px-3 py-2 text-sm font-medium text-muted transition-colors hover:bg-accent-soft hover:text-accent-dark"
          (click)="logout()"
        >
          Sair
        </button>
      } @else {
        <a
          routerLink="/login"
          routerLinkActive="bg-accent-soft text-accent-dark"
          class="rounded-[length:var(--radius-control)] px-3 py-2 text-sm font-medium text-muted transition-colors hover:bg-accent-soft hover:text-accent-dark"
        >
          Login
        </a>
        <a
          routerLink="/register"
          routerLinkActive="bg-accent-soft text-accent-dark"
          class="rounded-[length:var(--radius-control)] px-3 py-2 text-sm font-medium text-muted transition-colors hover:bg-accent-soft hover:text-accent-dark"
        >
          Cadastro
        </a>
      }
    </nav>
  </div>

  @if (menuOpen) {
    <nav
      [@navDrawer]
      id="mobile-nav"
      class="flex flex-col gap-1 border-t border-line px-4 py-3 md:hidden"
    >
      <a
        routerLink="/eventos"
        routerLinkActive="bg-accent-soft text-accent-dark"
        [routerLinkActiveOptions]="{ exact: false }"
        class="rounded-[length:var(--radius-control)] px-3 py-2 text-sm font-medium text-muted transition-colors hover:bg-accent-soft hover:text-accent-dark"
        (click)="closeMenu()"
      >
        Eventos
      </a>
      <a
        routerLink="/palestrantes"
        routerLinkActive="bg-accent-soft text-accent-dark"
        class="rounded-[length:var(--radius-control)] px-3 py-2 text-sm font-medium text-muted transition-colors hover:bg-accent-soft hover:text-accent-dark"
        (click)="closeMenu()"
      >
        Palestrantes
      </a>
      @if (isLoggedIn) {
        <a
          routerLink="/perfil"
          routerLinkActive="bg-accent-soft text-accent-dark"
          class="rounded-[length:var(--radius-control)] px-3 py-2 text-sm font-medium text-muted transition-colors hover:bg-accent-soft hover:text-accent-dark"
          (click)="closeMenu()"
        >
          Perfil
        </a>
        <button
          type="button"
          class="rounded-[length:var(--radius-control)] px-3 py-2 text-left text-sm font-medium text-muted transition-colors hover:bg-accent-soft hover:text-accent-dark"
          (click)="logout(); closeMenu()"
        >
          Sair
        </button>
      } @else {
        <a
          routerLink="/login"
          routerLinkActive="bg-accent-soft text-accent-dark"
          class="rounded-[length:var(--radius-control)] px-3 py-2 text-sm font-medium text-muted transition-colors hover:bg-accent-soft hover:text-accent-dark"
          (click)="closeMenu()"
        >
          Login
        </a>
        <a
          routerLink="/register"
          routerLinkActive="bg-accent-soft text-accent-dark"
          class="rounded-[length:var(--radius-control)] px-3 py-2 text-sm font-medium text-muted transition-colors hover:bg-accent-soft hover:text-accent-dark"
          (click)="closeMenu()"
        >
          Cadastro
        </a>
      }
    </nav>
  }
</header>
